odanek/duel6r

source/BonusList.cpp
source/Defines.h
source/Player.cpp
source/Player.h
source/Render.cpp
source/Render.h

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/30)

Show HP bar above player after being hit

---

source/Game.cpp
source/Gui.cpp
source/Gui.h
source/Menu.cpp
source/Menu.h
source/PersonList.h
source/Render.cpp

Playing players are removed from "non-playing" listbox.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/34)

Menu improvements

---

CMakeLists.txt
source/Elevator.cpp
source/Elevator.h
source/ElevatorList.cpp
source/ElevatorList.h
source/Player.cpp
source/Player.h
source/weapon/LegacyShot.cpp

- enjoy the shot hits / explosions
- added double jump to the speed boost power-up
- elevators give extra speed when going up and jumping
elevator crazy speed
- define D6_ELEV_SAFETY_LAST during compilation for extra fun with elevators

force & gravity

---

source/Player.cpp

- fix jumping up out of places with wall right above player's head
- fine tune the hit impact effect

- remove sideways speed boost when jumping on elevator

---

source/Game.cpp
source/Game.h
source/Menu.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/50)

Resume unfinished game

---

source/Defines.h
source/Level.cpp
source/Level.h
source/Player.cpp
source/Player.h
source/Round.cpp
source/Round.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/51)

Unstuck player

---

.gitignore
source/Defines.h
source/Menu.cpp

+ fixed "resume game" questions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/52)

Improved menu layout

---

source/Menu.cpp
source/Person.cpp
source/Person.h
source/PlayerEventListener.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/53)

Count total damage caused

---

.gitignore
source/Player.h

... only a half of the time added when player picks up the same bonus type.
Let's see how it impacts the game.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/54)

Stack same bonuses

---

source/BonusList.cpp
source/BonusList.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/55)

Avoid spawning new bonus on player

---

source/Application.cpp
source/World.cpp

- resolves FPS bound issues
- game is run at steady 60 ticks/s
- FPS is arbitrary

Separate game update rate from FPS

---

source/Player.cpp

- player should be able to perform the double jump also when jumping off elevators

Enable double-jumping also from elevators

---

source/Menu.cpp

- "joy_rescan" is performed after clicking 'D' in the main menu

Rescan for connected gamepads when mapping players' controls

---

CMakeLists.txt

CPU-specific instructions are used conditionally, only when available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/63)

ARM - initial support

---

source/GameMode.h
source/Round.cpp
source/gamemodes/GameModeBase.cpp
source/gamemodes/GameModeBase.h
source/gamemodes/TeamDeathMatch.cpp
source/gamemodes/TeamDeathMatch.h

- start pouring the water once some team has less than two alive players

Teamplay sudden death mode improvements

---

source/GameMode.h
source/Ranking.h
source/Round.cpp
source/WorldRenderer.cpp
source/gamemodes/GameModeBase.cpp
source/gamemodes/GameModeBase.h
source/gamemodes/TeamDeathMatch.cpp
source/gamemodes/TeamDeathMatch.h

- better stats tab during team play

Feature colorize teamplay ranking tab

---

source/gamemodes/Team.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/70)

fix - vector include for Team.h

---

source/Menu.cpp
source/Menu.h
source/gamemodes/Team.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/72)

Add player count to the label

---

source/GameMode.h
source/Level.cpp
source/Round.cpp
source/Round.h
source/gamemodes/GameModeBase.cpp
source/gamemodes/GameModeBase.h
source/gamemodes/TeamDeathMatch.cpp
source/gamemodes/TeamDeathMatch.h

Teams are spawned together ... more or less.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/77)

Feature: better team positions

---

source/gamemodes/TeamDeathMatch.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/78)

Feature improve teampositioning

---

source/gamemodes/TeamDeathMatch.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/odanek/duel6r/79)

More random player positioning

---

CMakeLists.txt
source/Bonus.cpp
source/Bonus.h
source/BonusList.cpp
source/BonusList.h
source/ElevatorList.cpp
source/ElevatorList.h
source/Game.cpp
source/GameMode.h
source/GameSettings.h
source/Menu.cpp
source/Menu.h
source/Player.cpp
source/Player.h
source/PlayerControls.cpp
source/World.cpp
source/collision/WorldCollision.cpp
source/collision/WorldCollision.h
source/gamemodes/GameModeBase.cpp
source/gamemodes/GameModeBase.h
source/gamemodes/TeamDeathMatch.cpp
source/gamemodes/TeamDeathMatchPlayerEventListener.cpp
source/gamemodes/TeamDeathMatchPlayerEventListener.h
source/gui/CheckBox.cpp
source/gui/CheckBox.h

drop weapons

---

CMakeLists.txt
source/Game.cpp
source/Game.h
source/Player.cpp
source/Player.h
source/PlayerAnimations.cpp
source/PlayerAnimations.h
source/PlayerSkin.cpp
source/PlayerSkin.h
source/TextureManager.cpp
source/TextureManager.h
source/aseprite/animation.h

- add PlayerAnimations
- add animation::AnimationView to allow clean configuration of animation layers visibility (hairs/headband) before generating the texture

Player animations - small refactoring

---

source/WorldRenderer.cpp

Fix off-by-one bug in display of current round number

Fix visual off-by-one bug

---

source/Game.cpp
source/Game.h
source/Player.cpp
source/Player.h
source/WorldRenderer.cpp
source/collision/WorldCollision.cpp
source/collision/WorldCollision.h

Fix displayed round number

---

CMakeLists.txt
resources/shaders/gles3/colorFragment.glsl
resources/shaders/gles3/colorVertex.glsl
resources/shaders/gles3/materialFragment.glsl
resources/shaders/gles3/materialVertex.glsl
source/Video.cpp
source/renderer/es3/GLES3Buffer.cpp
source/renderer/es3/GLES3Buffer.h
source/renderer/es3/GLES3Program.cpp
source/renderer/es3/GLES3Program.h
source/renderer/es3/GLES3Renderer.cpp
source/renderer/es3/GLES3Renderer.h
source/renderer/es3/GLES3Shader.cpp
source/renderer/es3/GLES3Shader.h
source/renderer/es3/GLES3Types.h

- 99% copy of the gl4 renderer
- differences: minimal modifications of shaders, GLEW not supporting GLES - few necessary hacks in GLES3Program

GLES 3.0 Renderer

---

CMakeLists.txt
source/BonusList.cpp
source/Game.cpp
source/Player.h
source/Video.cpp
source/net/ClientGameProxy.cpp
source/net/ClientGameProxy.h
source/net/Event.h
source/net/NetClient.cpp
source/net/Peer.cpp
source/net/Peer.h
source/net/ServerGameProxy.cpp
source/net/ServerGameProxy.h
source/net/Type.h
source/net/event/GameState.h
source/net/event/GameStateUpdate.h
source/net/event/PlayerInputsUpdate.h
source/net/event/RequestNextRound.h
source/net/event/events.h
source/net/object/PlayerScore.cpp
source/net/object/PlayerScore.h

- fix round start freezing
- fix round kills (dots) rendering
- fix ammo rendering
- allow for switching to next round (shift+f1 / action on round over summary)
- game state integration - proper Json serialization in Game::getGameState

Net masterserver
